[workspace]
resolver = "3"
members = [
    "code-first-capnp",
    "examples/demo-types",
    "examples/demo-run",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
facet = "0.29"
heck = "0.5"
capnp = "0.21"
capnpc = "0.21"