[package]
name = "demo"
version.workspace = true
edition.workspace = true

[dependencies]
code-first-capnp = { path = "../../code-first-capnp" }
code-first-capnp-macros.workspace = true
capnp.workspace = true
